import { Metadata } from "next";
import React from "react";
import HomeView from "../views/home/HomeView";

export const metadata: Metadata = {
  title: "Home page",
  description: "Generated by create next app",
};

const HomePage = async () => {
  return <HomeView />;
};

export default HomePage;
